services:
  app-queue-consumer:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - ./app/.env
      - ./app/.env.local
    image: buzzingpixel-site-backups-queue-consumer
    environment:
      HOSTNAME: buzzingpixel-site-backups-queue-consumer
#    volumes:

  app-schedule-runner:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - ./app/.env
      - ./app/.env.local
    image: buzzingpixel-site-backups-schedule-runner
    environment:
      HOSTNAME: buzzingpixel-site-backups-schedule-runner
#    volumes:
