services:
  app-queue-consumer:
    restart: always
    depends_on:
      - redis
    env_file:
      - ./app/.env
      - ./app/.env.local
    image: buzzingpixel-site-backups-queue-consumer
    container_name: buzzingpixel-site-backups-queue-consumer
    environment:
      HOSTNAME: buzzingpixel-site-backups-queue-consumer
    volumes:
      - /Users/tj/.ssh/id_rsa:/root/.ssh/id_rsa
      - /Users/tj/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - /Volumes/Promenade/git/site-backups/storage:/storage
      - ../:/var/www:delegated

  app-schedule-runner:
    restart: always
    depends_on:
      - redis
    env_file:
      - ./app/.env
      - ./app/.env.local
    image: buzzingpixel-site-backups-schedule-runner
    container_name: buzzingpixel-site-backups-schedule-runner
    environment:
      HOSTNAME: buzzingpixel-site-backups-schedule-runner
    volumes:
      - /Users/tj/.ssh/id_rsa:/root/.ssh/id_rsa
      - /Users/tj/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - /Volumes/Promenade/git/site-backups/storage:/storage
      - ../:/var/www:delegated

  redis:
    container_name: buzzingpixel-site-backups-redis
    image: redis
    volumes:
      - redis-volume:/data
    networks:
      default:
        aliases:
          - buzzingpixel-site-backups-redis

volumes:
  redis-volume:
