services:
  app-queue-consumer:
    depends_on:
      - redis
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - ./app/.env
      - ./app/.env.local
    image: ghcr.io/buzzingpixel/site-backups-queue-consumer
    environment:
      HOSTNAME: buzzingpixel-site-backups-queue-consumer
    volumes:
      - /Users/tj/.ssh/id_rsa:/root/.ssh/id_rsa
      - /Users/tj/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - /Volumes/ivy-ext-01/site-backups:/storage

  app-schedule-runner:
    depends_on:
      - redis
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - ./app/.env
      - ./app/.env.local
    image: ghcr.io/buzzingpixel/site-backups-schedule-runner
    environment:
      HOSTNAME: buzzingpixel-site-backups-schedule-runner
    volumes:
      - /Users/tj/.ssh/id_rsa:/root/.ssh/id_rsa
      - /Users/tj/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - /Volumes/ivy-ext-01/site-backups:/storage

  redis:
    image: redis
    volumes:
      - redis-volume:/data
    networks:
      default:
        aliases:
          - buzzingpixel-site-backups-redis

volumes:
  redis-volume:
