name: Build images and deploy to production

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_NAMESPACE: ghcr.io/buzzingpixel

jobs:
  build-app:
    name: Build app image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: docker/app/Dockerfile
          cache-from: type=registry,ref=ghcr.io/buzzingpixel/site-backups-app
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/site-backups-app
            ${{ env.IMAGE_NAMESPACE }}/site-backups-app:${{ github.sha }}

  build-app-dependent-queue-consumer:
    name: Build app-queue-consumer image
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: docker/app-queue-consumer/Dockerfile
          build-args: |
            APP_IMAGE=${{ env.IMAGE_NAMESPACE }}/site-backups-app:${{ github.sha }}
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/site-backups-queue-consumer
            ${{ env.IMAGE_NAMESPACE }}/site-backups-queue-consumer:${{ github.sha }}

  build-app-dependent-schedule-runner:
    name: Build app-schedule-runner image
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/docker-build-push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          file: docker/app-schedule-runner/Dockerfile
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            APP_IMAGE=${{ env.IMAGE_NAMESPACE }}/site-backups-app:${{ github.sha }}
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/site-backups-schedule-runner
            ${{ env.IMAGE_NAMESPACE }}/site-backups-schedule-runner:${{ github.sha }}

  deploy:
    name: Deploy to production
    runs-on: Ivy
    needs:
      - build-app
      - build-app-dependent-queue-consumer
      - build-app-dependent-schedule-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy deploy files to production directory
        # Work from our deploy directory
        working-directory: /Volumes/ivy-ext-01/site-backups-deploy
        run: |
          # Fail on any error
          set -e;

          # Copy environment files for Docker
          cp ${{ github.workspace }}/docker/app/.env docker/app/.env;
          cp ${{ github.workspace }}/docker/docker-compose.prod.yml docker/docker-compose.prod.yml;

          # Log in to GitHub Container Registry so we can pull images
          # Disable macOS Keychain credential store to allow non-interactive login
          mkdir -p ~/.docker;
          echo '{"credsStore":""}' > ~/.docker/config.json;
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin;

          # Pull images
          docker pull ${{ env.IMAGE_NAMESPACE }}/site-backups-app:${{ github.sha }};
          docker pull ${{ env.IMAGE_NAMESPACE }}/site-backups-queue-consumer:${{ github.sha }};
          docker pull ${{ env.IMAGE_NAMESPACE }}/site-backups-schedule-runner:${{ github.sha }};
          
          docker stack deploy \
              --compose-file docker/docker-compose.prod.yml \
              --prune \
              --with-registry-auth \
              --resolve-image always \
              site-backups;
